apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-vs-acme-sync
  namespace: istio-system
#   labels:
#     azure.workload.identity/use: "true"
#   annotations:
#     azure.workload.identity/client-id: client_id
#     azure.workload.identity/tenant-id: tenant_id
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vs-acme-sync-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vs-acme-sync-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: workload-identity-vs-acme-sync
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: vs-acme-sync-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vs-acme-sync
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vs-acme-sync
  template:
    metadata:
      labels:
        name: vs-acme-sync
    spec:
      serviceAccountName: workload-identity-vs-acme-sync
      containers:
      - name: vs-acme-sync
        image: acrinfraaahp.azurecr.io/vs-acme-sync:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi